events {
    worker_connections 1024;
}

http {
    client_body_temp_path /tmp/nginx_client_body_temp;
    proxy_temp_path /tmp/nginx_proxy_temp;
    fastcgi_temp_path /tmp/nginx_fastcgi_temp;
    uwsgi_temp_path /tmp/nginx_uswgi_temp;
    scgi_temp_path /tmp/nginx_scgi_temp;

    access_log /dev/stdout;
    error_log stderr;

    server {
        listen 8080;
        server_name _;

        location = /commons {
            return 308 /commons/;
        }

        location /commons/ {
            # /commons/api.php?... -> https://commons.wikimedia.org/api.php?...
            proxy_pass https://commons.wikimedia.org/;

            # Needed for HTTPS upstream/SNI.
            proxy_ssl_server_name on;

            # Because we define proxy_set_header below, keep nginx's important defaults explicit.
            proxy_set_header Host commons.wikimedia.org;
            proxy_set_header Connection close;

            # Hide requester IP / proxy-chain headers.
            proxy_set_header X-Forwarded-For "";
            proxy_set_header X-Real-IP "";
            proxy_set_header Forwarded "";
            proxy_set_header X-Client-IP "";
            proxy_set_header Client-IP "";
            proxy_set_header True-Client-IP "";
            proxy_set_header CF-Connecting-IP "";
            proxy_set_header Fastly-Client-IP "";
            proxy_set_header X-Cluster-Client-IP "";
            proxy_set_header X-Original-Forwarded-For "";
            proxy_set_header X-Forwarded "";
            proxy_set_header X-Forwarded-Host "";
            proxy_set_header X-Forwarded-Proto "";
            proxy_set_header X-Forwarded-Server "";
            proxy_set_header Via "";
        }

        location / {
            return 404;
        }
    }
}